## Import Necessary libraries

In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# load data

In [62]:
df=pd.read_csv("C:\\Users\\akhil\\Downloads\\House_Price_train.csv")

In [64]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [66]:
df.shape

(1460, 81)

In [68]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [70]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [72]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [74]:
df_num=df.select_dtypes(include=[np.number])
df_cat=df.select_dtypes(include=['object'])

In [76]:
df_num.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [78]:
df_cat.describe(include='all')

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1460,91,1460,1460,1460,1460,1460,1460,1460,...,1379,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,2,2,4,4,2,5,3,25,9,...,6,3,5,5,3,3,4,4,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,1454,50,925,1311,1459,1052,1382,225,1260,...,870,605,1311,1326,1340,3,157,49,1267,1198

In [80]:
df_num.isnull().sum().sort_values(ascending=False)

LotFrontage      259
GarageYrBlt       81
MasVnrArea         8
Id                 0
OpenPorchSF        0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageCars         0
GarageArea         0
WoodDeckSF         0
EnclosedPorch      0
HalfBath           0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
BedroomAbvGr       0
FullBath           0
MSSubClass         0
BsmtFinSF2         0
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
BsmtFinSF1         0
BsmtUnfSF          0
BsmtHalfBath       0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
SalePrice          0
dtype: int64

In [82]:
df_cat.isnull().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
MasVnrType        872
FireplaceQu       690
GarageType         81
GarageCond         81
GarageQual         81
GarageFinish       81
BsmtFinType2       38
BsmtExposure       38
BsmtFinType1       37
BsmtQual           37
BsmtCond           37
Electrical          1
KitchenQual         0
CentralAir          0
Functional          0
HeatingQC           0
Heating             0
PavedDrive          0
SaleType            0
MSZoning            0
Street              0
Condition2          0
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
BldgType            0
Foundation          0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
ExterQual           0
ExterCond           0
SaleCondition       0
dtype: int64

# Imputation of Numerical columns

In [85]:
print(df_num['LotFrontage'].mean())
print(df_num['LotFrontage'].median())

70.04995836802665
69.0

In [106]:
for col in ["LotFrontage","GarageYrBlt","MasVnrArea"]:
    df_num[col].fillna(df_num[col].median(),inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\1123892463.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_num[col].fillna(df_num[col].median(),inplace=True)

In [108]:
df_num.isnull().sum().sort_values(ascending=False)

Id               0
WoodDeckSF       0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
OpenPorchSF      0
MSSubClass       0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
HalfBath         0
FullBath         0
BsmtHalfBath     0
BsmtFullBath     0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
SalePrice        0
dtype: int64

# Imputation of Categorical columns

In [89]:
for col in ["PoolQC"]:
    df_cat[col].fillna('No Value',inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\1161263546.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna('No Value',inplace=True)

In [91]:
for col in ["GarageCond",]:
    df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\1075783591.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)

In [93]:
for col in ["PoolQC","MiscFeature","Alley","Fence"]:
    df_cat[col].fillna('No Value',inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\3104450496.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna('No Value',inplace=True)

In [95]:
for col in ["MasVnrType","FireplaceQu","GarageType","GarageQual","GarageFinish","BsmtExposure","BsmtFinType2","BsmtFinType1","BsmtQual","BsmtCond","Electrical"]:
    df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)

C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)
C:\Users\akhil\AppData\Local\Temp\ipykernel_13028\2478006621.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cat[col].fillna(df_cat[col].value_counts().idxmax(),inplace=True)

In [104]:
df_cat.isnull().sum().sort_values(ascending=False)

MSZoning         0
FireplaceQu      0
BsmtFinType1     0
BsmtFinType2     0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
KitchenQual      0
Functional       0
GarageType       0
BsmtCond         0
GarageFinish     0
GarageQual       0
GarageCond       0
PavedDrive       0
PoolQC           0
Fence            0
MiscFeature      0
SaleType         0
BsmtExposure     0
BsmtQual         0
Street           0
Condition2       0
Alley            0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
BldgType         0
Foundation       0
HouseStyle       0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
ExterQual        0
ExterCond        0
SaleCondition    0
dtype: int64

# Correlationship between numerical columns and numerical target

In [111]:
df_num_corr=df_num.corr()

In [113]:
df_num_corr["SalePrice"]

Id              -0.021917
MSSubClass      -0.084284
LotFrontage      0.334771
LotArea          0.263843
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
MasVnrArea       0.472614
BsmtFinSF1       0.386420
BsmtFinSF2      -0.011378
BsmtUnfSF        0.214479
TotalBsmtSF      0.613581
1stFlrSF         0.605852
2ndFlrSF         0.319334
LowQualFinSF    -0.025606
GrLivArea        0.708624
BsmtFullBath     0.227122
BsmtHalfBath    -0.016844
FullBath         0.560664
HalfBath         0.284108
BedroomAbvGr     0.168213
KitchenAbvGr    -0.135907
TotRmsAbvGrd     0.533723
Fireplaces       0.466929
GarageYrBlt      0.466754
GarageCars       0.640409
GarageArea       0.623431
WoodDeckSF       0.324413
OpenPorchSF      0.315856
EnclosedPorch   -0.128578
3SsnPorch        0.044584
ScreenPorch      0.111447
PoolArea         0.092404
MiscVal         -0.021190
MoSold           0.046432
YrSold          -0.028923
SalePrice        1.000000
Name: SalePrice, dtype: float64

In [115]:
df_num_cols = []
df_num_cols.extend(df_num_corr[(df_num_corr["SalePrice"]>0.3)].index.values)
df_num_cols.extend(df_num_corr[(df_num_corr["SalePrice"]<-0.3) ].index.values)

In [117]:
df_num_cols

['LotFrontage',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'SalePrice']

# Correlationship between categorical columns and continous target variable using one way ANNOVA

In [120]:
from scipy.stats import f_oneway

In [122]:
df_cat['sp']=df_num['SalePrice']

In [124]:
groups = [df_cat['sp'][df_cat['BsmtExposure'] == category] for category in df_cat['BsmtExposure'].unique()]

# Perform ANOVA
f_stat, p_value = f_oneway(*groups)
print(f"F-statistic: {f_stat}, P-value: {p_value}")

F-statistic: 76.57793447709939, P-value: 5.39423843153302e-46

In [126]:
c_list=[]
nc_list=[]
for c1 in list(df_cat.columns):
    if c1 == 'sp':
        continue
    else:
        groups = [df_cat['sp'][df_cat[c1] == category] for category in df_cat[c1].unique()]
        f_stat, p_value = f_oneway(*groups)
        print(f"column : {c1}, F-statistic: {f_stat}, P-value: {p_value}")
        if p_value < 0.05:
            c_list.append(c1)
        else:
            nc_list.append(c1)

column : MSZoning, F-statistic: 43.84028167245718, P-value: 8.817633866272648e-35
column : Street, F-statistic: 2.4592895583691994, P-value: 0.11704860406782483
column : Alley, F-statistic: 15.176613889987992, P-value: 2.9963796805460783e-07
column : LotShape, F-statistic: 40.13285166226295, P-value: 6.447523852011766e-25
column : LandContour, F-statistic: 12.850188333283924, P-value: 2.7422167521379096e-08
column : Utilities, F-statistic: 0.29880407484898486, P-value: 0.5847167739689381
column : LotConfig, F-statistic: 7.809954123467792, P-value: 3.163167473604189e-06
column : LandSlope, F-statistic: 1.9588170374149438, P-value: 0.1413963584114019
column : Neighborhood, F-statistic: 71.78486512058272, P-value: 1.558600282771154e-225
column : Condition1, F-statistic: 6.118017137125925, P-value: 8.904549416138853e-08
column : Condition2, F-statistic: 2.0738986215227877, P-value: 0.043425658360948464
column : BldgType, F-statistic: 13.011077169620851, P-value: 2.0567364604967015e-10
column : HouseStyle, F-statistic: 19.595000995981223, P-value: 3.376776535121222e-25
column : RoofStyle, F-statistic: 17.80549722914421, P-value: 3.653523047099125e-17
column : RoofMatl, F-statistic: 6.727304893420313, P-value: 7.231444779987188e-08
column : Exterior1st, F-statistic: 18.61174286624578, P-value: 2.5860887286376316e-43
column : Exterior2nd, F-statistic: 17.500839571369834, P-value: 4.8421856706985465e-43
column : MasVnrType, F-statistic: 90.37821868529072, P-value: 9.992113997549483e-38
column : ExterQual, F-statistic: 443.33483141504627, P-value: 1.4395510967787893e-204
column : ExterCond, F-statistic: 8.798714214177485, P-value: 5.106680608671862e-07
column : Foundation, F-statistic: 100.25385058740888, P-value: 5.791895002232233e-91
column : BsmtQual, F-statistic: 413.94564835837843, P-value: 2.078120077126687e-194
column : BsmtCond, F-statistic: 13.791801383643444, P-value: 7.166577741866081e-09
column : BsmtExposure, F-statistic: 76.57793447709939, P-value: 5.39423843153302e-46
column : BsmtFinType1, F-statistic: 70.51842537038553, P-value: 3.598398455129613e-66
column : BsmtFinType2, F-statistic: 2.3900074267234896, P-value: 0.03599298669495113
column : Heating, F-statistic: 4.259818559406287, P-value: 0.000753472106445497
column : HeatingQC, F-statistic: 88.39446198869796, P-value: 2.667062092104357e-67
column : CentralAir, F-statistic: 98.30534356615253, P-value: 1.8095061559267854e-22
column : Electrical, F-statistic: 23.074438198968412, P-value: 1.6412076757769925e-18
column : KitchenQual, F-statistic: 407.80635155838866, P-value: 3.0322127528400614e-192
column : Functional, F-statistic: 4.0578754277920215, P-value: 0.0004841696801078294
column : FireplaceQu, F-statistic: 41.13390402821061, P-value: 1.0611469709006871e-32
column : GarageType, F-statistic: 59.312956794559646, P-value: 2.578442945744067e-56
column : GarageFinish, F-statistic: 303.6194065735224, P-value: 5.99331922426961e-111
column : GarageQual, F-statistic: 8.45759783210094, P-value: 9.588016104813055e-07
column : GarageCond, F-statistic: 8.203442711097685, P-value: 1.5322787250522445e-06
column : PavedDrive, F-statistic: 42.02417941762533, P-value: 1.803568890651533e-18
column : PoolQC, F-statistic: 10.509852607071148, P-value: 7.7009894157147e-07
column : Fence, F-statistic: 13.433275547560223, P-value: 9.379976594788224e-11
column : MiscFeature, F-statistic: 2.593622339924057, P-value: 0.0350036718754261
column : SaleType, F-statistic: 28.863054116984088, P-value: 5.039766889462451e-42
column : SaleCondition, F-statistic: 45.57842830969571, P-value: 7.988268404991176e-44

In [128]:
c_list

['MSZoning',
 'Alley',
 'LotShape',
 'LandContour',
 'LotConfig',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [130]:
nc_list

['Street', 'Utilities', 'LandSlope']

In [132]:
df_cat1=df_cat[c_list]

In [134]:
df_cat1.columns

Index(['MSZoning', 'Alley', 'LotShape', 'LandContour', 'LotConfig',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive',
       'PoolQC', 'Fence', 'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [136]:
df_cat1.head()

,MSZoning,Alley,LotShape,LandContour,LotConfig,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,No Value,Reg,Lvl,Inside,CollgCr,Norm,Norm,1Fam,2Story,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal
1,RL,No Value,Reg,Lvl,FR2,Veenker,Feedr,Norm,1Fam,1Story,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal
2,RL,No Value,IR1,Lvl,Inside,CollgCr,Norm,Norm,1Fam,2Story,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal
3,RL,No Value,IR1,Lvl,Corner,Crawfor,Norm,Norm,1Fam,2Story,...,Detchd,Unf,TA,TA,Y,No Value,No Value,No Value,WD,Abnorml
4,RL,No Value,IR1,Lvl,FR2,NoRidge,Norm,Norm,1Fam,2Story,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal

# LabelEncoding

In [139]:
from sklearn.preprocessing import LabelEncoder

In [141]:
le=LabelEncoder()

In [143]:
df_cat1_e=df_cat1.apply(le.fit_transform)

In [145]:
df_cat1_e.head()

,MSZoning,Alley,LotShape,LandContour,LotConfig,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,3,1,3,3,4,5,2,2,0,5,...,1,1,4,4,2,3,4,1,8,4
1,3,1,3,3,2,24,1,2,0,2,...,1,1,4,4,2,3,4,1,8,4
2,3,1,0,3,4,5,2,2,0,5,...,1,1,4,4,2,3,4,1,8,4
3,3,1,0,3,0,6,2,2,0,5,...,5,2,4,4,2,3,4,1,8,0
4,3,1,0,3,2,15,2,2,0,5,...,1,1,4,4,2,3,4,1,8,4

In [147]:
df_cat1.shape

(1460, 40)

# Onehot encoding method1

In [150]:
df_encoded = pd.get_dummies(df_cat1, columns=df_cat1.columns)

In [152]:
df_encoded.shape

(1460, 248)

# method2

In [154]:
from sklearn.preprocessing import OneHotEncoder

In [159]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [161]:
encoded_array = encoder.fit_transform(df_cat1)

encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out(df_cat1.columns))

In [163]:
encoded_df.shape

(1460, 248)

# Outlier treatment IQR

In [166]:
def remove_outliers_iqr(df, columns):
    for col in columns:
        Q1 = df[col].quantile(0.25)  # First quartile (25th percentile)
        Q3 = df[col].quantile(0.75)  # Third quartile (75th percentile)
        IQR = Q3 - Q1               # Interquartile range
        lower_bound = Q1 - 1.5 * IQR  # Lower bound
        upper_bound = Q3 + 1.5 * IQR  # Upper bound

        # Remove outliers
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
    
    return df

In [168]:
columns_to_check = ['LotFrontage',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'SalePrice'] 

df_no_outliers = remove_outliers_iqr(df_num, columns_to_check)

print("Original DataFrame:")
print(df_num.shape)
print("\nDataFrame after Outlier Treatment:")
print(df_no_outliers.shape)

Original DataFrame:
(1460, 38)

DataFrame after Outlier Treatment:
(1033, 38)

In [170]:
encoded_df.shape

(1460, 248)

In [172]:
df_no_outliers.shape

(1033, 38)

In [189]:
df_f_cat=encoded_df.loc[df_no_outliers.index,:]

# MinMaxScaler scales features to a fixed range, typically [0,1](but can be customized).

In [191]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [198]:
columns_to_scale =['LotFrontage',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'SalePrice']

In [200]:
minmax_scaler = MinMaxScaler()
df_minmax_scaled = df_no_outliers.copy()
df_minmax_scaled[columns_to_scale] = minmax_scaler.fit_transform(df_no_outliers[columns_to_scale])